listen:
  port: 9000

webserver:
  https: false
  hostname: 'video.beyondbitcoin.io'
  port: 80

database:
  hostname: 'localhost'
  port: 27017
  suffix: '-dev'

# From the project root directory
storage:
  certs: 'certs/'
  videos: 'videos/'
  logs: 'logs/'
  previews: 'previews/'
  thumbnails: 'thumbnails/'
  torrents: 'torrents/'
